title: "Cade Armstrong"
description: "Astrodynamics • Controls • Multi-agent decision making"
url: "https://<username>.github.io"

theme: jekyll-theme-cayman

plugins:
  - jekyll-feed

# Optional: makes pretty URLs like /about/ instead of /about.html
permalink: pretty

